### ISSUE TITLE
Error when run stable diffusion colab example on cpu colab

### ISSUE THREAD

**Issue by svjack** [neuralmagic/examples#22]
When run the following notebook
https://colab.research.google.com/github/neuralmagic/notebooks/blob/main/notebooks/deepsparse-stable-diffusion/notebook.ipynb

Yield error when 
```python
from optimum.deepsparse import DeepSparseStableDiffusionPipeline
```
because optimum depends on cupy 
Nowadays, cupy can not used without cuda backend.

Can you tackle this problem ?

**Comment by mgoin** [comment]
Hi @svjack Colab is a bit of a unique environment because of all of the preinstalled packages - tensorflow, pytorch, and many cuda libraries. In this case you can simply remove cupy in another line as it isn't needed with `pip uninstall -y cupy-cuda11x`

Here is a full colab notebook example for DeepSparseSentenceTransformers where we also ensure that a cpu-only version of pytorch is installed as well:
https://colab.research.google.com/drive/1sfN8zDK7MIyatiSIbt2xWh0i6GnaBnTR?usp=sharing

**Comment by svjack** [comment]
> Hi @svjack Colab is a bit of a unique environment because of all of the preinstalled packages - tensorflow, pytorch, and many cuda libraries. In this case you can simply remove cupy in another line as it isn't needed with `pip uninstall -y cupy-cuda11x`
> 
> Here is a full colab notebook example for DeepSparseSentenceTransformers where we also ensure that a cpu-only version of pytorch is installed as well: https://colab.research.google.com/drive/1sfN8zDK7MIyatiSIbt2xWh0i6GnaBnTR?usp=sharing

I have try the deepsparse stable-diffusion example in the local machine with cpu only on a intel-i7 cpu 
It consume too many memory (about 30g for sd2.1) and the inference speed Not as fast as expected.
Can you improve this ?

**Comment by svjack** [comment]
> Hi @svjack Colab is a bit of a unique environment because of all of the preinstalled packages - tensorflow, pytorch, and many cuda libraries. In this case you can simply remove cupy in another line as it isn't needed with `pip uninstall -y cupy-cuda11x`
> 
> Here is a full colab notebook example for DeepSparseSentenceTransformers where we also ensure that a cpu-only version of pytorch is installed as well: https://colab.research.google.com/drive/1sfN8zDK7MIyatiSIbt2xWh0i6GnaBnTR?usp=sharing

Can you make this embedding model support clip ? It seems only support text embedding nowadays. 😊

**Comment by jeanniefinks** [comment]
Hi @svjack 
We wanted to circle back on this:
We are deprecating support for stable diffusion; clip support is not on the roadmap.
Thank you.
Jeannie / Neural Magic
